---

- name: Gather facts for all hosts
  hosts: all
  gather_facts: false
  roles:
    - provision


- name: Gather facts for all hosts
  hosts: jenkins
  gather_facts: false
  roles:
    - jenkins
  tags: jenkins

